### ISSUE TITLE
Code coverage doesn't seem to work

### ISSUE THREAD

**Issue by danarth** [ASE-ESRS/MARTIN-client#11]
I obviously was the one who looked into this issue at the start of the project, but whilst Android Studio locally produces code coverage reports that show the percentage of tests that we have covered, coveralls still shows 0% coverage.

I'd appreciate it if anyone else could look into this issue

**Comment by danarth** [comment]
# Status Update
This issue is **still** ongoing. However, I am still looking into fixing it. I am currently looking into CodeClimate as a potential CI solution (instead of Coveralls) for Test Coverage reports. It makes sense given that we already use CodeClimate for maintainability of our codebase.

Any feedback on this suggestion would be very much appreciated @ASE-ESRS/esrs-team

**Comment by LoicVerrall** [comment]
#30 :) 👏
