### ISSUE TITLE
Dynamically adjust heat map intensity

### ISSUE THREAD

**Issue by LoicVerrall** [ASE-ESRS/MARTIN-client#15]
Dynamically adjust the heat map intensity (colours) based on the data-points currently shown to the user.

**Comment by msp26ssx** [comment]
#18 The max and min prices are now calculated, however currently they are not used within HeatMap generation. This can be done when the settings menu for this is complete. //TODO comment added re this

**Comment by msp26ssx** [comment]
Also, Martin mentioned adding _"labelling that gives an indication
how colours correspond to prices"_.

**Comment by msp26ssx** [comment]
As above, the following might be used to implement this: https://developers.google.com/maps/documentation/android-api/infowindows
