### ISSUE TITLE
Postcode/pindrop location selection

### ISSUE THREAD

**Issue by LoicVerrall** [ASE-ESRS/MARTIN-client#16]
Allow users to enter a postcode or drop a pin anywhere on the map to find prices around that particular location.

**Comment by danarth** [comment]
My pull request #22 partially fixes this issue. In my PR the user can select any new point on the map and the application will automatically search for house prices paid data at that location using the given settings.

Please consider splitting this issue into 2. I believe the pindropping issue is completely separate from the ability to type in a postcode as they are 2 very different parts of the UI.
