### ISSUE TITLE
Set a `LatLngBounds` for the Google Maps Camera

### ISSUE THREAD

**Issue by danarth** [ASE-ESRS/MARTIN-client#23]
Obviously the app only uses house prices paid data for the UK, so it makes sense to just limit the Google Maps camera so that the user is always looking at the UK.

The [`setLatLngBoundsForCameraTarget(LatLngBounds)`](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#setLatLngBoundsForCameraTarget(com.google.android.gms.maps.model.LatLngBounds))method of the `GoogleMap` class should achieve this result.

Firstly, we need to define northeasterly and southwesterly points just outside of the UK that the camera will not be able to travel by.

**Comment by msp26ssx** [comment]
SW: 49.82380908513249, -10.8544921875
NE: 59.478568831926395, 2.021484375
as per: https://gist.github.com/UsabilityEtc/6d2059bd4f0181a98d76?short_path=890afc3
