### ISSUE TITLE
Refactor code so that it works on the emulator

### ISSUE THREAD

**Issue by danarth** [ASE-ESRS/MARTIN-client#32]
Resolving this issue will allow us to write instrumentation tests.

**Comment by LoicVerrall** [comment]
By this, do you mean abstract functionality into smaller functions that we can individually test?

**Comment by danarth** [comment]
Not quite - sorry I wasn't very specific - I am very tired 😴 I will update in the morning with more details. But basically I discovered a bug that means even if you choose a custom location on the map the app will throw `NullPointerException`s unless it successfully geolocated you in the first place.

This means we cannot test on the emulator properly so it will be handy to refactor the code such that it does not rely on the fact the user has location services on. This will enable us to perform instrumentation tests that Travis will run on the emulator.

**Comment by LoicVerrall** [comment]
@DanielArthurUK did #31 fix this?

**Comment by danarth** [comment]
Yes it did!!
