### ISSUE TITLE
Document Code Ownership

### ISSUE THREAD

**Issue by LoicVerrall** [ASE-ESRS/MARTIN-client#6]
Martin mentioned that it's important to explicitly state _who_ 'owns' the code (in relation to code reviews).

https://matterhorn-presentation.uscs.susx.ac.uk/engage/theodul/ui/core.html?id=fceac7cb-9118-4cfd-b7f1-defb14f8a7a5

**Comment by danarth** [comment]
Do we have any updates on how we might do this @LoicVerrall ?

**Comment by LoicVerrall** [comment]
I don't think this is important. Happy to close @DanielArthurUK?

**Comment by danarth** [comment]
I have been going through the code and JavaDoc-ing as much as possible. This should be another issue really as documentation should be key. Anyway, I interpreted code ownership as the `@author` tags we can write in the JavaDoc documentation?

For example, say I wrote a class `Prices`:

````java
/**
 * The Prices class does so and so blah blah blah ...
 * @author Daniel Arthur
 **/
public class Prices {
    ...
}
````

**Comment by LoicVerrall** [comment]
Perfect, well I'll just leave this to you to finish then?

**Comment by danarth** [comment]
@LoicVerrall Sounds good. When you and @msp26ssx get a chance could you please go through the client and add @author annotations to the classes and methods you've written?

**Comment by msp26ssx** [comment]
I've done this, not sure about Loic, if so, ok to close this now?

**Comment by LoicVerrall** [comment]
@msp26ssx, yep! Go ahead and close it :)
